//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TrafficLight
{
    [Serializable]
    public class TrafficLightArrayMsg : Message
    {
        public const string k_RosMessageName = "TrafficLight/TrafficLightArray";
        public override string RosMessageName => k_RosMessageName;

        public TrafficLightMsg[] lights;

        public TrafficLightArrayMsg()
        {
            this.lights = new TrafficLightMsg[0];
        }

        public TrafficLightArrayMsg(TrafficLightMsg[] lights)
        {
            this.lights = lights;
        }

        public static TrafficLightArrayMsg Deserialize(MessageDeserializer deserializer) => new TrafficLightArrayMsg(deserializer);

        private TrafficLightArrayMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.lights, TrafficLightMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.lights);
            serializer.Write(this.lights);
        }

        public override string ToString()
        {
            return "TrafficLightArrayMsg: " +
            "\nlights: " + System.String.Join(", ", lights.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
