//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TrafficLight
{
    [Serializable]
    public class TrafficLightStatusMsg : Message
    {
        public const string k_RosMessageName = "TrafficLight/TrafficLightStatus";
        public override string RosMessageName => k_RosMessageName;

        public int id;
        public int status;

        public TrafficLightStatusMsg()
        {
            this.id = 0;
            this.status = 0;
        }

        public TrafficLightStatusMsg(int id, int status)
        {
            this.id = id;
            this.status = status;
        }

        public static TrafficLightStatusMsg Deserialize(MessageDeserializer deserializer) => new TrafficLightStatusMsg(deserializer);

        private TrafficLightStatusMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.id);
            deserializer.Read(out this.status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.id);
            serializer.Write(this.status);
        }

        public override string ToString()
        {
            return "TrafficLightStatusMsg: " +
            "\nid: " + id.ToString() +
            "\nstatus: " + status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
