//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.TrafficLight
{
    [Serializable]
    public class TrafficLightStatusArrayMsg : Message
    {
        public const string k_RosMessageName = "TrafficLight/TrafficLightStatusArray";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public TrafficLightStatusMsg[] lights;

        public TrafficLightStatusArrayMsg()
        {
            this.header = new Std.HeaderMsg();
            this.lights = new TrafficLightStatusMsg[0];
        }

        public TrafficLightStatusArrayMsg(Std.HeaderMsg header, TrafficLightStatusMsg[] lights)
        {
            this.header = header;
            this.lights = lights;
        }

        public static TrafficLightStatusArrayMsg Deserialize(MessageDeserializer deserializer) => new TrafficLightStatusArrayMsg(deserializer);

        private TrafficLightStatusArrayMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.lights, TrafficLightStatusMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.lights);
            serializer.Write(this.lights);
        }

        public override string ToString()
        {
            return "TrafficLightStatusArrayMsg: " +
            "\nheader: " + header.ToString() +
            "\nlights: " + System.String.Join(", ", lights.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
